#!/usr/bin/env bash

_fortune=`fortune -a`

cat << EOF > /tmp/fortune_page.html
<html>
<head>
	<style media="screen" type="text/css">
		body {
			position: absolute;
			top: 35%;
			left: 10%;
			right: 10%;
			font-family: monospace;
			color:#aaaaaa;
			background-color:#1a1a1a;
		}
	</style>
</head>
<body>
$_fortune
</body>
</html>
EOF

exec $BROWSER /tmp/fortune_page.html
