#!/usr/bin/env bash

case $1 in
	naiyuusei )
		i3-msg [window_role="naiyuusei"] focus
		i3-msg mode "default" ;;
	browser )
		i3-msg [class="Firefox"] focus
		i3-msg mode "default" ;;
	* )
		i3-msg [class="$1"] focus
		i3-msg mode "default" ;;
esac
