#!/usr/bin/env bash

if [[ $(pgrep mpv) ]]; then
	case $1 in
		--play )
			echo "cycle pause" > $_mpvfifo ;;
		--stop )
			echo "stop" > $_mpvfifo ;;
		--next )
			echo "playlist_next" > $_mpvfifo ;;
		--prev )
			echo "playlist_prev" > $_mpvfifo ;;
		--seekf )
			echo "seek 30" > $_mpvfifo ;;
		--seekb )
			echo "seek -30" > $_mpvfifo ;;
		--skipf )
			echo "add chapter 1" > $_mpvfifo ;;
		--skipb )
			echo "add chapter -1" > $_mpvfifo ;;
		* )
			;;
	esac
elif [[ $(pgrep audacious) ]]; then
	case $1 in
		--play )
			audacious -t ;;
		--stop )
			audacious -s ;;
		--next )
			audacious -f ;;
		--prev )
			audacious -r ;;
		* )
			;;
	esac
else
	case $1 in
		--play )
			mpc toggle ;;
		--stop )
			mpc stop ;;
		--next )
			mpc next ;;
		--prev )
			mpc prev ;;
		--seekf )
			mpc seek +00:00:10 ;;
		--seekb )
			mpc seek -00:00:10 ;;
		* )
			;;
	esac
fi
