#!/bin/sh

case "$1" in
	-f | --fortune )
		_fortune="$(fortune -a)"
cat << EOF > /tmp/fortune.html
<html>
<head>
	<style media="screen" type="text/css">
		body {
			position: absolute;
			top: 35%;
			left: 10%;
			right: 10%;
			font-family: monospace;
			color:#aaaaaa;
			background-color:#1a1a1a;
			font-size:xx-large;
		}
	</style>
</head>
<body>
$_fortune
</body>
</html>
EOF

		for _browser in "$BROWSER" firefox chromium konquerer rekonq midori jumanji dwb luakit uzbl w3m; do
			if which "$_browser" > /dev/null 2>&1; then
				exec "$_browser"
			fi
		done ;;
	"" )
		for _browser in "$BROWSER" firefox chromium konquerer rekonq midori jumanji dwb luakit uzbl w3m; do
			if which "$_browser" > /dev/null 2>&1; then
				exec "$_browser"
			fi
		done ;;
	* )
		for _browser in "$BROWSER" firefox chromium konquerer rekonq midori jumanji dwb luakit uzbl w3m; do
			if which "$_browser" > /dev/null 2>&1; then
				exec "$_browser" "$@"
			fi
		done ;;
esac
