#!/usr/bin/env bash

alias less=$PAGER
alias zless=$PAGER
alias ls='ls --color=auto'
alias du1='du -h --max-depth=1'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias msi='makepkg -si'
alias syu='pacaur -Syu'
alias auau='sudo aptitude update && sudo aptitude upgrade'
alias winej='WINEDEBUG=-all LC_ALL=ja_JP.utf8 wine'
alias xrl='xrandr --output DVI-D-0 --rotate left'
alias xrn='xrandr --output DVI-D-0 --rotate normal'
alias ix="curl -sF 'f:1=<-' http://ix.io"
alias fluidstart="(nohup fluidsynth -is -a pulseaudio -r 44100 soundfont-unison /usr/share/soundfonts/Unison.sf2 >/dev/null 2>&1 &)"
alias fluidstop="pkill fluidsynth"
alias midiplay="aplaymidi --port 128:0"
alias mpt="mplayer -ao pulse:tsukikage"
alias mpm="mplayer -ao pulse:meiousei"
alias mpo="mplayer -ao pulse:okaasan"

powerdown () {
	case "$HOSTNAME" in
		"tsukikage" )
			pkill firefox
			poweroff ;;
		"meiousei" )
			sudo shutdown -h now ;;
		"hoshiakari" )
			echo "powerdown: this is your SERVER, br0" ;;
		* )
			echo "powerdown: no defined behavior for this host" ;;
	esac
}

if [[ "$HOSTNAME" != "hoshiakari" ]]; then
	alias ncmpcpp="ssh hoshiakari -t 'LC_ALL=en_US.UTF-8 ncmpcpp' 2>/dev/null" ;
fi

pl () {
	case "$1" in
		"" )
			declare -A _status
			_status=()
			while read -r; do
				[[ ! "$REPLY" ]] && break
				_status+=( ["${REPLY%%: *}"]="${REPLY#*: }" )
			done < <((echo "status"; echo "currentsong"; sleep .1; echo "q"; echo "close") |\
				 telnet -e q $MPD_HOST 6600)
			_status+=( ["0"]="${_status[Artist]} - ${_status[Title]} - ${_status[Album]}" )
			case "${_status[state]}" in
				"play" )
					mpc playlist -f "[%artist% - ]%title%[[ - %album%][ (%time%)]]" |\
						GREP_COLORS="ms=01;32:mc=01:32" egrep -nT --color "${_status[0]}|" ;;
				"pause" )
					mpc playlist -f "[%artist% - ]%title%[[ - %album%][ (%time%)]]" |\
					 	GREP_COLORS="ms=01;33:mc=01;33" egrep -nT --color "${_status[0]}|" ;;
				* )
					mpc playlist -f "[%artist% - ]%title%[[ - %album%][ (%time%)]]" |\
						egrep -nT --color "${_status[0]}|" ;;
			esac ;;
		"a" )
			mpc add "$2" ;;
		"c" )
			mpc clear -q;;
		"i" )
			mpc insert "$2" ;;
		"t" )
			mpc toggle -f "[%artist% - ]%title%[ - %album%]" | head -n 1 ;;
		"n" )
			mpc next -f "[%artist% - ]%title%[ - %album%]" | head -n 1 ;;
		"p" )
			mpc prev -f "[%artist% - ]%title%[ - %album%]" | head -n 1 ;;
		"s" )
			mpc status -f "[%artist% - ]%title%[ - %album%]" ;;
		[0-9]* )
			mpc play -f "[%artist% - ]%title%[ - %album%]" "$1" | head -n 1 ;;
		* )
			mpc "$@" ;;
	esac
}

complete -o nospace -F _mpc pl
