#!/usr/bin/env bash

# WELCOME TO HELL.

prompt_powerline() {
	local _none="\[\e[0m\]"    # unsets color to term's fg color

	local _k="\[\e[0;30;40m\]" _r="\[\e[0;31;40m\]" _g="\[\e[0;32;40m\]" _y="\[\e[0;33;40m\]" \
		  _b="\[\e[0;34;40m\]" _m="\[\e[0;35;40m\]" _c="\[\e[0;36;40m\]" _w="\[\e[0;37;40m\]"
	
	local _git_ps1_s="\$(__git_ps1 %s)"

	if [[ $TERM == 'linux' ]]; then
		_div='>' _cwd='\[\e[0;36m\w >';
	else
		_div='⮁' _cwd="$_c \w\[\e[0;30m\]⮀$_none"
	fi

	if [[ $SSH_TTY ]]; then
		local _host="$_y \h $_div" _title_host="\h";
	else
		local _host="$_b$_div" _title_host=">";
	fi

	if (( UID == 1000 )); then # I can generalize this later ...
		local _user="$_g$_div" _title_user=">"
	elif (( UID == 0 )); then
		local _user="$_r root $_div" _title_user="root";
	else
		local _user="$_g \u $_div" _title_user="\u";
	fi

	_ret='$((( _ret_value )) && printf " \[\e[1;31;40m\]$_ret_value $_div\[\e[0;0m\]")'
	
	_git="\$(__git_ps1 '\[\e[0;35;40m\] %s $_div')"

	local _title="\[\e]2;$_title_host>$_title_user: \w\007\]"

	PS1="$_title$_host$_user$_ret$_git$_cwd "
	
	export PS4='+$BASH_SOURCE[$LINENO]: '
}

PROMPT_COMMAND='_ret_value=$?'
GIT_PS1_SHOWDIRTYSTATE=yes
prompt_powerline
unset prompt_powerline
unset _cwd
